### ISSUE TITLE
Migrate from travis-ci.org to travis-ci.com until 2020-12-31

### ISSUE THREAD

**Issue by christiansiegel** [baloise/rocket-chat-rest-client#63]
travis-ci.**org** will be closed down December 31st, 2020

Announcement: https://mailchi.mp/3d439eeb1098/travis-ciorg-is-moving-to-travis-cicom
Migration guide: https://docs.travis-ci.com/user/migrate/open-source-repository-migration

**Comment by kullmanp** [comment]
Should we archive this project anyway?

**Comment by kullmanp** [comment]
The project is now migrated to travis-ci.com. But the master branch does not build (and it didn't build for some time already). The PR #69 restores a working build by running the integration tests against an older version of rocket.chat. 

It would be great if we could test against the latest version. But right now it doesn't work because of issues like https://github.com/RocketChat/Rocket.Chat/issues/19537. In a nutshell: our node version is too old for the current rocket chat versions. 

Using a matching node installation requires a bit of change in the build setup. Currently we use rocketchat/base:12.16 as the base for a custom docker image. There is no newer version of the base image with a suitable version of node. I see two options:
- Update the node version in the Dockerfile (include something like apt install node ...)
- Instead of the custom image we could use the ready-made rocketchat/rocket.chat:latest image and move all configuration in the Dockerfile to the pom.
